### ISSUE TITLE
Can't generate a sheet with Japanese symbols

### ISSUE THREAD

**Issue by mrtrizer** [soimy/msdf-bmfont-xml#11]
Hi! I've tried to add few Japanese symbols into charset string (こんにちは) and found that these symbols are not presented in an atlas. I've tried with several fonts without success. Are there any reasons behind this? Can this be easily fixed in some way? May be I have to try with any concrete fonts?
Thanks for answer!

**Comment by soimy** [comment]
I'm not sure yet, but will try to test the case.
BTW, can you upload the font you are using? @mrtrizer

**Comment by mrtrizer** [comment]
Last time I tried with this one
https://www.freejapanesefont.com/iroha-maru-mikami-download/

**Comment by soimy** [comment]
Make sure your charset file is encoded using UTF-8. Don't use Windows Notepad to paste in charset.
