### ISSUE TITLE
Missing characters in export png 

### ISSUE THREAD

**Issue by yooni126** [soimy/msdf-bmfont-xml#13]
Hi
I have a persian font that you can download it from this link:
https://www.dropbox.com/s/lvlv8yulgjn3svh/B%20Koodak%20Bold.TTF?dl=0

I want to change this font to bitmapFont so I write this code:
msdf-bmfont -o koodak.png --charset-file charset.txt --texture-size 1024,1024 --smart-size koodak.ttf

also i set charset.txt to these characters:
ببب ب
تتت ت
ضضض ض
صصص ص
ثثث ث
ققق ق
ففف ف
غغغ غ
ععع ع
ههه ه
خخخ خ
ححح ح
ججج ج
چچچ چ
ششش ش
سسس س
ییی ئ ی ي
ببب ب
للل ل
اآ
ننن ن
ممم م
ککک ک
گگگ گ
ظظظ ظ
ططط ط
زرژ
و
ذد
پپپ پ
َُِّ
":><؟{}|+_()&*!@#$%×÷÷`|;'[].,/\،-=
12345567890 

all set is done , but when i see the export png it show me a few characters not all characters that i set in charset.txt, why?

![nazanin 0](https://user-images.githubusercontent.com/3766387/34422028-2076256e-ec28-11e7-9e6f-b78fc9875d34.png)

**Comment by soimy** [comment]
Turns out the font you used is missing a lot of standard ASC-II characters.
You can check it out at https://opentype.js.org/glyph-inspector.html by uploading ur font.

**Comment by yooni126** [comment]
ok , i test the new font with a lot of standard ASC-II characters 
https://www.dropbox.com/s/1fuigy78xi2jtx5/iransans.fnt?dl=0

but the problem still exist!
