### ISSUE TITLE
Missing characters in export png

### ISSUE THREAD

**Issue by yooni126** [soimy/msdf-bmfont-xml#14]
in last issue you said that I must use a font with a lot of standard ASC-II characters
so I use this font :
https://www.dropbox.com/s/1fuigy78xi2jtx5/iransans.fnt?dl=0

and set charset.txt to these text:
ببب ب
تتت ت
ضضض ض
صصص ص
ثثث ث
ققق ق
ففف ف
غغغ غ
ععع ع
ههه ه
خخخ خ
ححح ح
ججج ج
چچچ چ
ششش ش
سسس س
ییی ئ ی ي
ببب ب
للل ل
اآ
ننن ن
ممم م
ککک ک
گگگ گ
ظظظ ظ
ططط ط
زرژ
و
ذد
پپپ پ
َُِّ
":><؟{}|+_()&*!@#$%×÷÷`|;'[].,/\،-=
12345567890

But my export png is still a problem :(
![iransans 0](https://user-images.githubusercontent.com/3766387/34452048-34b71dd8-ed4c-11e7-9168-aecb04a28112.png)

**Comment by yooni126** [comment]
oh I forgot that one of my friends gave me a solution but its very strange:
https://github.com/myflashlab/RTL-BitmapFont/issues/1

**Comment by soimy** [comment]
@yooni126 can you post the generated `.fnt` file and the exact command/argument in the generation?
There are no more missing glyphs but apparently, not all glyphs are in the font atlas. I need to know why.

**Comment by yooni126** [comment]
yes of course
you can download it from this link :
https://www.dropbox.com/s/ngywyipv8b1wl2z/soimy.zip?dl=0

please read readMe file in 2 folders;

**Comment by yooni126** [comment]
did you see zip file? was it clear?

**Comment by soimy** [comment]
yes, clear enough.
Just back to work, I'll look into it soon and keep you update.
BTW, I'll also try to find a solution on RTL xoffset and xadvance mentioned by myflashlab/RTL-BitmapFont#1

**Comment by soimy** [comment]
Close via f4bc573d0125d7eeb84f978c371759c59b52bd09
Please read the updated Readme for instruction. Add a flag(--rtl) in CLI to fix Arabic/Persian bugs.
