### ISSUE TITLE
Run from electron

### ISSUE THREAD

**Issue by Apidcloud** [soimy/msdf-bmfont-xml#18]
Good evening!

I have no problems using this package from node, but I wonder if there a good way to make this run from electron?

The following error is raised when I attempt to do so:
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\Workspace\GitHub\_Scarlett\scarlett-editor\node_modules\canvas-prebuilt\canvas\build\Release\canvas.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Workspace\GitHub\_Scarlett\scarlett-editor\node_modules\canvas-prebuilt\canvas\lib\bindings.js:3:18)
    at Object.<anonymous> (D:\Workspace\GitHub\_Scarlett\scarlett-editor\node_modules\canvas-prebuilt\canvas\lib\bindings.js:5:3)
```

I tried to run electron-rebuild on it, but it still happens.
I wonder if I would need a specific build from canvas-prebuilt.
Any ideas?

**Comment by Apidcloud** [comment]
Also opened an issue on canvas-prebuilt itself: https://github.com/node-gfx/node-canvas-prebuilt/issues/30

I'll try to build it targeting node 7.9 and use it in this package.

**Comment by soimy** [comment]
Haven't tried this on electron yet. Maybe it relates to path canvas-prebuild loading local dynamic libraries.
`msdf-bmfont-xml` is designed as a back-end program. If you decide to use it as front-end, it's better to substitute `node-canvas` to DOM canvas or WebGL framework like Pixi.js. They are used to render glyphs to final atlas, nothing more.

**Comment by Apidcloud** [comment]
I think it’s because electron uses a different node version within (1.7.11 uses 7.9), so node canvas has to be built targeting that version instead. I’ve opened an issue in that repository as well, to check whether that’s possible. I’ll keep you updated :) thanks!

**Comment by Apidcloud** [comment]
Good news! It does seem to work under electron when targeting it (e.g., 1.7.11). See https://github.com/node-gfx/node-canvas-prebuilt/issues/30 for the discussion.

If the author is able to release a version with said target, could you do the same?

Thanks! 💯

**Comment by Apidcloud** [comment]
Thanks!

Still got no news from `canvas-prebuilt`, but I'm curious about replacing those libraries. Anything in mind yet?

**Comment by soimy** [comment]
Haven't got time on this yet, but my plan is replace `node-canvas` with `node-pngjs` on back-end, or `pixi.js` on front-end. `opentype.js` to more light-weight `typr.js` on runtime-parser or `fontkit` maybe.

**Comment by Apidcloud** [comment]
Still no answer from `canvas-prebuilt`. Can we release an electron version ourselves for the time being?

**Comment by Apidcloud** [comment]
Meanwhile I got it working by publishing my own builds of `canvas`.

**Comment by Apidcloud** [comment]
Ah. Still regarding that message, the bar doesn't really go further (from 0% to 100%) despite actually working.

**Comment by soimy** [comment]
Ah, that's absolutely normal. `space` does not have any glyph so a blank bitmap warning is given. The progress bar just shows that the warning is triggered at 0/95.  Just ignore it.

**Comment by soimy** [comment]
Fixed the progress bar info above warning message via fa5e9a90755e20762b96d75995a4f07a54b96a73
