### ISSUE TITLE
Binaries not executable in 2.3.2

### ISSUE THREAD

**Issue by donmccurdy** [soimy/msdf-bmfont-xml#19]
The binaries in the 2.3.2 release don't seem to be executable:

![screen shot 2018-02-09 at 4 26 02 pm](https://user-images.githubusercontent.com/1848368/36056057-f77b6dae-0db5-11e8-8045-19dcbb0a8512.png)

A manual `chmod` after installation fixes the issue. I don't see anything in the commit history to explain that. 😕

I am using macOS here.

**Comment by soccerob** [comment]
I'm not able to run anything with this latest version. after installing via npm, i get errors when attempting to run msdf-bmfont -v
i tried chmod with no success

 msdf-bmfont -v
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/msdf-bmfont-xml/node_modules/canvas-prebuilt/canvas/build/Release/canvas.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/msdf-bmfont-xml/node_modules/canvas-prebuilt/canvas/lib/bindings.js:3:18)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

**Comment by soimy** [comment]
@donmccurdy sorry, this is due to new version submitted to npm via windows... I'll fix that

**Comment by soimy** [comment]
Fixed via bca20ca24bfcf1e7d03ffd43550953dfbeecc6c6

**Comment by donmccurdy** [comment]
Thanks @soimy! With that update I no longer have to compile from the fork, and see no artifacts. 🙂 But it does not seem like this issue is fixed — none of the binaries appear to be executable.

**Comment by soimy** [comment]
尴尬！Fixed via 5f8f2901bf521ca2c98343685a23fd690ebe26f1
Thanks for reporting this @donmccurdy

**Comment by donmccurdy** [comment]
Working perfectly now, thanks! 🎊
