### ISSUE TITLE
Inconsistent results in linux vs macOS

### ISSUE THREAD

**Issue by donmccurdy** [soimy/msdf-bmfont-xml#21]
I'm trying to make a little hosted service to create bmfont files, and am getting oddly different results when running the same thing locally (macOS) vs Docker (linux, but thanks to Docker magic, i'm not actually sure what linux distro this is...).

Guessing I'll need to dig into the linux version and see if there are open issues there, but wanted to file something here in case you have any ideas. This is the new v2.3.2, haven't tested anything earlier.

| macOS | linux |
|-|-|
| <img width="1033" alt="screen shot 2018-02-10 at 2 45 55 pm" src="https://user-images.githubusercontent.com/1848368/36067411-a447b784-0e71-11e8-91f6-12801300cac1.png"> | <img width="1088" alt="screen shot 2018-02-10 at 2 46 08 pm" src="https://user-images.githubusercontent.com/1848368/36067413-a7378f1e-0e71-11e8-92a7-05e5eac6bb2c.png"> |

* Demo: http://msdf-bmfont.donmccurdy.com/
* Source: https://github.com/donmccurdy/msdf-bmfont-web

**Comment by donmccurdy** [comment]
^Changed base image from debian/jesse to ubuntu/xenial with no effect, so at least it's consistent.

**Comment by donmccurdy** [comment]
Related: https://github.com/Chlumsky/msdfgen/issues/59

**Comment by soimy** [comment]
Due to point tolerance issue on old linux binary from Chlumsky's repo, windows/mac version is using https://github.com/ckohnert/msdfgen

Check #17

**Comment by soimy** [comment]
Currently I'm having trouble to compile ckohnert's fork under ubunu 14.04 with gcc-4.8

**Comment by donmccurdy** [comment]
So the linux binary is still pointed to Chlumsky's binary, Windows/Mac to Ckohnert's? That would explain it, thanks. I'll try compiling the fork on my Docker image and see where that gets me...

**Comment by donmccurdy** [comment]
It's compiling on Xenial for me, so my web app is up and running. Thanks for your help! 🙂

**Comment by soimy** [comment]
Fixed via bca20ca24bfcf1e7d03ffd43550953dfbeecc6c6
