### ISSUE TITLE
Suggestion: changing sizing-defaults of command-line tool

### ISSUE THREAD

**Issue by PrimaryFeather** [soimy/msdf-bmfont-xml#25]
Hey Shen,

I'd like to suggest two small changes of the default values of the command-line tool. I guess I'm a little lazy, so I like to avoid having to type a lot of arguments when it shouldn't be necessary. :wink:

IMHO, most developers will just want to get the single (!) smallest texture that's able to pick up the glyphs. Furthermore, I don't know of any (at least somewhat modern) graphics hardware that can't load textures with at least 2048x2048 pixels. So I'd suggest changing two default settings from their current setting:

<pre>
textureSize     : 256,256
smartSize       : false
</pre> 

To:

<pre>
textureSize     : 2048,2048
smartSize       : true
</pre> 

Because then, a simple call like this: 

<pre lang="bash">
$> msdf-bmfont Arial.ttf
</pre> 

Would already produce the output most users will want to have — one font file, one texture file. And if that users is limited to POT-textures, just a single additional argument (`--pot`) will solve his problem. My guess is that 90% of the use-cases will work out of the box with these defaults.

Thanks for considering this! :smile:

Cheers,
Daniel

**Comment by soimy** [comment]
OK, will do

**Comment by PrimaryFeather** [comment]
Wonderful! Thanks a lot in advance! :smile:

**Comment by soimy** [comment]
Closed via d05ef86534d734e6cefd5c5468b3da205d5a6e88
