### ISSUE TITLE
Update the docs reference for textureWidth/textureHeight

### ISSUE THREAD

**Issue by roipeker** [soimy/msdf-bmfont-xml#26]
When using in nodeJS, options.textureWidth/options.textureHeight doesn't work, looking at index.js  seems the actual value is options.textureSize...
Maybe update index.js to have granular access to width/height, or README to reflect the correct prop name.

Update:
just realized .textureSize expected an array of [width,height], please update the README.

**Comment by soimy** [comment]
Thanks for the report!

**Comment by soimy** [comment]
Fixed via 67cd02887f5e34b1af3d3fefce8e29bbf22003be
