### ISSUE TITLE
It seem something wrong with Chinese font.

### ISSUE THREAD

**Issue by JanzTam** [soimy/msdf-bmfont-xml#34]
[SourceHanSansCN-Heavy-lite.ttf.zip](https://github.com/soimy/msdf-bmfont-xml/files/3051274/SourceHanSansCN-Heavy-lite.ttf.zip)

The font which is include  'Welcome$0123456789返回清空后退排行榜分数最高邀请好友开始'.

**Comment by soimy** [comment]
I don't think it's a legit font
<img width="400" alt="QQ20190407-205050@2x" src="https://user-images.githubusercontent.com/1550237/55683828-db31d580-5976-11e9-8498-2b28a1c9441b.png">
