### ISSUE TITLE
Crash when using npm run render

### ISSUE THREAD

**Issue by brupelo** [soimy/msdf-bmfont-xml#38]
Windows7, node v12.4.0 over here:

- cloned the repo
- npm install
- npm install -g devtool
- npm run render

And boom, crash:

![showcase](https://dl.dropboxusercontent.com/s/6xyn0qv4601vxl4/electron_2019-06-22_14-45-19.png)

Could you advice? :)

**Comment by soimy** [comment]
devtools is abandoned, sorry about that. And I’m too lazy to find a substation.

**Comment by soimy** [comment]
Try the newest commit @brupelo
