### ISSUE TITLE
Font data may write before chars parsed

### ISSUE THREAD

**Issue by rzer** [soimy/msdf-bmfont-xml#39]
`fontFile.data = utils.stringify(fontData, outputType); `
may happens before
`const asyncTextures = await Promise.all(textures);`
So chars data may be empty.

It's happens for me when i try to reuse texture for another font. My solution is to move first line after second.

**Comment by soimy** [comment]
Thanks for reporting! Just in time🙏
I'm looking for the missing chars data right now.
