### ISSUE TITLE
SVG Import?

### ISSUE THREAD

**Issue by delaneyj** [soimy/msdf-bmfont-xml#40]
I have a bunch of icons in SVG i'd like to be part of the atlas.  Is there an easy way to be able to append a folder of them during generation?

**Comment by soimy** [comment]
Currently, there is no easy way of importing SVGs. Your best bet is trying to convert them into font like font-awesome.
BTW this repo is going to be depreciated. Take a look at the next generation: https://github.com/soimy/atlasify it will have the feature you looking for.

**Comment by delaneyj** [comment]
Atlasify does look like exactly what I want, thank you.
