### ISSUE TITLE
Missing padding info

### ISSUE THREAD

**Issue by johh** [soimy/msdf-bmfont-xml#42]
Hey there!

I've noticed that `font.info.padding` is always `[0, 0, 0, 0]`.
Since some padding info is calculated [here](https://github.com/soimy/msdf-bmfont-xml/blob/ff3669c2bfffd06f29bacedcdf3f073379b45e7e/index.js#L326) shouldn't that info be made available in `font.info.padding`? It'd come in handy when aligning things or calculating metrics.

I'm happy to submit a PR.

**Comment by soimy** [comment]
Real padding might introduce some artifacts in msdf textures (Not tested), but should be useful when dealing with sdf or svg output, but they are rarely used.
If you think this is meaningful, PR is welcomed! Thank you.
