### ISSUE TITLE
HELP with SVG

### ISSUE THREAD

**Issue by bishalkc** [soimy/msdf-bmfont-xml#46]
Not sure what I am doing wrong here. 

>   -t, --field-type <type>       msdf(default) | sdf | psdf | svg (default: "msdf")

when I run 
`msdf-bmfont -t svg Downloads/RobotoMono-Bold.ttf`

`Using following settings `
`========================================

- version         : msdf-bmfont-xml v2.5.2
- outputType      : xml
- filename        : Downloads/RobotoMono-Bold
- fontSize        : 42
- charsetFile     : Unspecified, fallback to ASC-II
- textureSize     : 2048,2048
- texturePadding  : 1
- border          : 0
- distanceRange   : 4
- fieldType       : svg
- roundDecimal    : 0
- vector          : false
- reuse           : false
- smartSize       : false
- pot             : false
- square          : false
- rot             : false
- rtl             : false
- fontFile        : Downloads/RobotoMono-Bold.ttf

`

Can you please assist here?

Thanks

**Comment by soimy** [comment]
Sorry for the late reply, vector generation has been moved to `-v` option.
I'll update the `cli` and document.
