### ISSUE TITLE
Support fontBuffer as alternative to fontPath

### ISSUE THREAD

**Issue by donmccurdy** [soimy/msdf-bmfont-xml#47]
I'm migrating https://msdf-bmfont.donmccurdy.com/ (which is basically a web GUI for creating MSDF fonts...) to a newer version of my web hosting service. The new platform version doesn't allow writing anything to disk — but on the bright side it's much cheaper to run!

At this point I've got everything working, except that this package requires `fontPath` as a path on disk. The `opentype` dependency has a `opentype.parse(buffer)` method that should be able to handle a Buffer object instead.

If I write up a PR adding `fontBuffer` support, would you be open to merging that? Proposed API:

```js
generateBMFont(fontBuffer, opt, (error, textures, font) => {
  ...
});
```

**Comment by soimy** [comment]
Sure, PR is welcomed!

**Comment by donmccurdy** [comment]
Thanks! Opened https://github.com/soimy/msdf-bmfont-xml/pull/48.
