### ISSUE TITLE
Add support for OpenType fonts

### ISSUE THREAD

**Issue by PrimaryFeather** [soimy/msdf-bmfont-xml#7]
I just tried msdf-bmfont-xml with an OTF font (e.g. [this one](http://www.dafont.com/de/dk-otago.font)). When doing so, [this line](https://github.com/soimy/msdf-bmfont-xml/blob/b0a5993fd0c2d943b97fac998896a0d693611425/index.js#L102) will cause an error to be thrown. 

However, it seems that this is not necessary, because when I change the line to the following, it works just fine:

```js
if (font.outlinesFormat !== 'truetype' && font.outlinesFormat !== 'cff') {
    // ...
}
```

I'm not sure if this is the case for all OpenType fonts, but it's worth a try, perhaps. Cheers! :smile:

**Comment by PrimaryFeather** [comment]
Thanks in advance! :smile:

**Comment by soimy** [comment]
Added support for OTF/WOFF font format in version `2.3.0` 983d88771d931a6cb86963873b8d0e7c8f1a17a3
Test needed.

**Comment by PrimaryFeather** [comment]
I just tried the new version, and it works fine! Thanks!
