### ISSUE TITLE
Is it possible to make atlas for multiple characters glyps?

### ISSUE THREAD

**Issue by Zemledelec** [soimy/msdf-bmfont-xml#83]
It 's better to have whole words (towns, countries etc. labels) to render instead of many glyps one by one. Is it possible to get atlas for separate words with bmfont? Thanks!

**Comment by soimy** [comment]
msdf-bmfont-xml is not designed for this. Try [TexturePacker](https://www.codeandweb.com/texturepacker) or [Atlasify](https://github.com/soimy/atlasify)

**Comment by Zemledelec** [comment]
Thanks!
